#!/bin/bash
#SBATCH --job-name=cut3r_ss_xattn_v2_merge
#SBATCH --nodes=4
#SBATCH --gpus-per-node=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --time=16:00:00
#SBATCH --partition=boost_usr_prod
#SBATCH --qos=normal
#SBATCH --output=logs/train/%x_%j.out
#SBATCH --error=logs/train/%x_%j.err
#SBATCH --mem=0
#SBATCH --exclude=lrdn0249,lrdn0612,lrdn0568,lrdn2400,lrdn0288,lrdn0418,lrdn0119,lrdn0159,lrdn0080,lrdn0843,lrdn3322
#SBATCH --exclusive

set -euo pipefail

export NOTE="${NOTE:-CUT3R SpatialStack cross_attn_v2: camera+patch memory, merge alignment, positive residual gammas.}"
export SUFFIX="${SUFFIX:-cut3r_spatialstack_cross_attn_v2_merge_cam_gamma}"
export TRAIN_RUN_NAME="${TRAIN_RUN_NAME:-cut3r_spatialstack_cross_attn_v2_merge_cam_gamma_${SLURM_JOB_ID:-manual}}"

export MODEL_CUT3R_SPATIALSTACK_FUSION_TYPE="${MODEL_CUT3R_SPATIALSTACK_FUSION_TYPE:-cross_attn_v2}"
export MODEL_CUT3R_SPATIALSTACK_LAYERS="${MODEL_CUT3R_SPATIALSTACK_LAYERS:-6,9,12}"
export MODEL_CUT3R_SPATIALSTACK_LLM_LAYERS="${MODEL_CUT3R_SPATIALSTACK_LLM_LAYERS:-0,1,2}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_IMPL="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_IMPL:-torch_mha}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_PATCH_ALIGN="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_PATCH_ALIGN:-merge}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_USE_CAMERA_TOKENS="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_USE_CAMERA_TOKENS:-True}"
export MODEL_CUT3R_SPATIALSTACK_REQUIRE_CAMERA_TOKENS="${MODEL_CUT3R_SPATIALSTACK_REQUIRE_CAMERA_TOKENS:-True}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_USE_MLP="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_USE_MLP:-True}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_NORM_TYPE="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_NORM_TYPE:-qwen_rmsnorm}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_POS_EMBED="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_POS_EMBED:-sincos2d}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_ZERO_INIT="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_ZERO_INIT:-False}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_GAMMA_ATTN_INIT="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_GAMMA_ATTN_INIT:-0.05}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_GAMMA_MLP_INIT="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_GAMMA_MLP_INIT:-0.05}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_GAMMA_LEARNABLE="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_GAMMA_LEARNABLE:-True}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_DROPOUT="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_DROPOUT:-0.0}"
export MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_SAME_FRAME_ONLY="${MODEL_CUT3R_SPATIALSTACK_CROSS_ATTN_SAME_FRAME_ONLY:-True}"
export MODEL_TORCH_COMPILE="${MODEL_TORCH_COMPILE:-False}"
export MODEL_USE_POINTMAP_SUPERVISION="${MODEL_USE_POINTMAP_SUPERVISION:-False}"

SCRIPT_DIR="${SLURM_SUBMIT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
exec bash "$SCRIPT_DIR/train_cut3r_spatialstack.sh"
